### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app on F-Droid. You can later add a button for Google Play the same way :
`[Get it on Google Play]()`

It also adds a link to get the latest APK from the Releases Section.

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

I see your app is also in the IzzyOnDroid repo; You might want to let @izzysoft know if you want to keep your app in his repo as well.

### CODE REVIEW

**Comment by TecCheck** [comment]
That looks good. Thank you very much

> I see your app is also in the IzzyOnDroid repo; You might want to let @IzzySoft know if you want to keep your app in his repo as well.

Do you mean, IzzySoft will remove FastLyrics from his repo?

**Comment by IzzySoft** [comment]
> if you want to keep your app in his repo as well.

In which case you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there as well :wink:

> Do you mean, IzzySoft will remove FastLyrics from his repo?

I usually do once an app reaches F-Droid.org – unless it was explicitly requested I shall keep it, and that is feasible. If your app is configured at F-Droid.org as reproducible build and the APK size is decent, I see no issue with that. Otherwise it might lead to confusion (due to different signatures), or if the APK is rather large I'd prefer to resolve the "size conflict". There might be good reasons for exceptions, though – but those are the "general rules".

Hence, looking forward to your decision with this. As it was explicitly brought up here, I'll wait for that before taking any actions (I've set myself a marker now).

**Comment by IzzySoft** [comment]
@TecCheck so do you want me to keep the app in my repo? Else i would be removed now. As the badge pointing to my repo s still shown on your Readme, I guess I should rather mark it to stay?

**Comment by IzzySoft** [comment]
@TecCheck now would be the time to decide. I see the badge is still there in the Readme – so you want me to keep the app in my repo? It pops up here for removal on each check-run, so I'd appreciate to know whether to remove or to mark for keep, to keep the report short and workable :wink:

**Comment by TecCheck** [comment]
I'm sorry. I totally forgot to answer. Does it have any advantages to have it in your repo? If not I guess you can remove it.

**Comment by IzzySoft** [comment]
If you've established reproducible builds with F-Droid.org, the advantage would be slightly faster updates (my updater just pulls the APK from your releases, which happens within 24h of your making it available there – while F-Droid needs to build it first, which usually takes 3..5 days). So not that big deal I'd say.

If it's not set up as reproducible build it might cause some confusion, as cross-updates are then not possible. Whoever had it installed from my repo would need to uninstall and re-install to switch to the F-Droid.org build, and vice versa.

Decision is yours. If I shall remove it here, I'd suggest you first remove the badge from the Readme, to avoid people following it ending up on an error page :wink:

**Comment by IzzySoft** [comment]
@TecCheck did you decide? I see the badge is still there. Usually, time for removal fro my repo was 2 weeks ago. Can you please let me know?

**Comment by IzzySoft** [comment]
@TecCheck any word? People will be quite confused if they follow that link and get a 404, which soon will happen. This is my last ping; apps are removed from my repo once they reach F-Droid unless explicitly requested otherwise. If you don't answer I must assume you don't care, so removal is due then.

**Comment by TecCheck** [comment]
I'm so sorry. I was busy with other stuff but thank you very much for letting me know. I will remove the badge now

**Comment by IzzySoft** [comment]
Thanks @TecCheck! And yes, no bad feelings (I know very well what "being busy" means – stuff stacked up here the past days as well as I was fighting against some "deadline" with a special task :see_no_evil:). I'll then wait for the badge to disappear, and remove the app from my repo after that (oh: gone already, OK, then I'll do it now). Should you one day need it back in my repo for some reason, just let me know: it's re-established easily as its metadata is just archived, not deleted.

**Comment by TecCheck** [comment]
That sound good. Thanks again and good luck with your own work

**Comment by IzzySoft** [comment]
Thanks! And to you!

**Pull request merged**
